name: pet_shelter_new
description: Pet Shelter App
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^1.1.6
  image_picker: ^0.8.7+2
  cached_network_image: ^3.2.3

  # State management
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  provider: ^6.0.5

  # Navigation
  routemaster: ^1.0.1
  email_validator: ^2.1.17

  # Code generation, serialization
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

  # DI
  get_it: ^7.2.0

  # Maps
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  location: ^4.4.0

  # Network
  dio: ^5.1.1

  # Storage
  shared_preferences: ^2.1.0
  geocoding: ^2.1.0
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  uuid: ^3.0.7
  permission_handler: ^10.2.0
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bottom_bar/
    - assets/images/pet_type/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800