// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbAgVoN3kUCx8i1jqKKKkptX3RzvqZT9k',
    appId: '1:997843736166:web:f58ef573ab66ee822f3fa7',
    messagingSenderId: '997843736166',
    projectId: 'petshelter-6ce17',
    authDomain: 'petshelter-6ce17.firebaseapp.com',
    storageBucket: 'petshelter-6ce17.appspot.com',
    measurementId: 'G-307DDTHRH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-xiwddx-8MAwlfLlG1_SsepXollpmS4',
    appId: '1:997843736166:android:5456f3e6971996392f3fa7',
    messagingSenderId: '997843736166',
    projectId: 'petshelter-6ce17',
    storageBucket: 'petshelter-6ce17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD654m6qN3cFq1Ww6o7vgy7NEOGuCQ2j6o',
    appId: '1:997843736166:ios:bc26b16ce0265a842f3fa7',
    messagingSenderId: '997843736166',
    projectId: 'petshelter-6ce17',
    storageBucket: 'petshelter-6ce17.appspot.com',
    iosClientId: '997843736166-t7oidthv81j335gr7m6e61mqmbns8um6.apps.googleusercontent.com',
    iosBundleId: 'com.issart.pet-shelter',
  );
}
